title: MDEforALL
description: A model-driven alternative to programming in blocks using rule-based model transformation
theme: jekyll-theme-cayman
show_downloads: false
logo: mdeforall-logo.png
github:
  is_project_page: false
